apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: pipeline
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "Atdev25@!"
  PG_USER: "admin"
  PG_PASSWORD: "atdev2025"
  QWEN_API_KEY: "MOAI-MAC-SECRET-KEY-2025"
